<?php	

//define("DB_DSN",'mysql:host=localhost;dbname=daniellg1617'  ); 
//define("DB_USUARIO", "daniellg1617" ); 
//define("DB_CONTRASENIA", "cJ6ifb" ); 
	
define("DB_DSN",'mysql:host=localhost;dbname=phpmyadmin'); 
    define("DB_USUARIO", "phpmyadmin" ); 
    define("DB_CONTRASENIA", "piezas750" ); 
    
        define("TAMANIO_PAGINA", 5 ); 
	    define("TABLA_MIEMBROS", "MIEMBROS" );
        	define("TABLA_COMENTARIOS", "comentarios" );
                define("TABLA_DISCOS","discos")

        ?>